### ISSUE TITLE
Error when running example notebook

### ISSUE THREAD

**Issue by roshan9128** [azizilab/decipher#5]
Following the instructions on the example notebook leads to this error:

`TypeError: category dtype does not support aggregation 'mean'`

for this step:

`dc.tl.trajectories(
    adata,
    dc.tl.TConfig("Healthy", "AVP", "MPO", "origin", "Healthy"),
    dc.tl.TConfig("AML1", "AVP", "CD68", "origin", "AML1"),
)`.

Any ideas would be appreciated, thanks!

**Comment by ANazaret** [comment]
Hello, thank you for raising this issue. This bug is actually fixed in the repo, but the package on PyPi is not yet updated. 

I will release a new version on PyPi later today (so you can use pip to install it).

If you need the bug to be fixed now, you can clone this repository, and install it from source with `pip install -e path/to/cloned_repo`, otherwise run `pip install scdecipher --upgrade` once the new version is released.

Thanks!
